### PR TITLE
Handle malformed JWT tokens

### PR DESCRIPTION
**Pull request by maquchizi**
Right now, the package forwards `ValueError` and `JWTError` to the caller as is which causes a 500 error on the server.

This PR handles those errors cleanly and returns a helpful message.

Sample tokens that would raise these errors:
- `Bearer asdasd` will raise `ValueError: not enough values to unpack (expected 2, got 1)`
- `Bearer aasdfasdf.asdfasdf` will raise `jose.exceptions.JWTError: Error decoding token headers.`

### CODE REVIEW

**Comment by revmischa** [comment]
Thanks!

**Comment by maquchizi** [comment]
Thank you for merging, @revmischa. Would you mind publishing the changes to PyPI? We're using this in production and it's really handy.
Also, thank you for maintaining the package.

**Comment by revmischa** [comment]
ok try 1.14

**Comment by maquchizi** [comment]
Works like a charm. Thank you!!

**Pull request merged**
